"""empty message

Revision ID: 2235ce1fa9c1
Revises: 
Create Date: 2021-10-23 01:47:36.581457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2235ce1fa9c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('picture', sa.String(length=256), nullable=True),
    sa.Column('google_id', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    op.create_table('connect_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_login', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connect_history_user_id'), 'connect_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connect_history_user_id'), table_name='connect_history')
    op.drop_table('connect_history')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
